title: Aquib Shaikh
author: Aquib Shaikh
email: shaikhaquib394@gmail.com
description: Backend Engineer | .NET, Python, Go | Microservices & High-Performance APIs
baseurl: "" # Leave empty for GitHub Pages root
url: "https://aquib.sh"

twitter_username: aquib-sh
github_username:  aquib-sh

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ["technical", "personal"]

header_pages:
  - index.markdown
  - about.markdown
  - _pages/blog.md

# Show post excerpts on blog page
show_excerpts: true
